# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Show all folders
        run: ls -R
      - uses: actions/upload-artifact@v2
        with:
          path: ./build/libs/lab4-1.0-SNAPSHOT.jar
          name: build_jar

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test

  TestUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Show all folders
        run: ls -R
      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v2
        with:
          path: world.txt
          name: hello_world

  TestDownload:
    needs: TestUpload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hello_world
      - name: Show all folders
        run: ls -R
      - name: Display world.txt
        run: cat world.txt
